spring:
  application:
    name: jwt-auth-backend

  datasource:
    url: jdbc:mysql://localhost:3306/jwt_auth_db
    username: root
    password: Milad13711992*

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  main:
    allow-circular-references: true  # ğŸš« ÙÙ‚Ø· Ø¨Ø±Ø§ÛŒ Ù…ÙˆØ§Ø±Ø¯ Ø§Ø¶Ø·Ø±Ø§Ø±ÛŒ Ùˆ Ù…ÙˆÙ‚ØªÛŒ!

server:
  port: 9090

logging:
  level:
    org.springframework.beans.factory.support: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: 3z8Xg2k94HqP56!sdA0@9KlqW78u2aQp
  expiration: 86400000 # 1 day in milliseconds
